# Generated by Django 5.0.6 on 2026-02-06 08:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eft_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bank",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="debitaccount",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="eftbatch",
            name="is_active",
        ),
        migrations.AlterUniqueTogether(
            name="efttransaction",
            unique_together={("batch", "sequence_number")},
        ),
        migrations.RemoveField(
            model_name="scheme",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="zone",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="eftbatch",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eftbatch",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eftbatch",
            name="currency",
            field=models.CharField(default="MWK", max_length=3),
        ),
        migrations.AddField(
            model_name="eftbatch",
            name="debit_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches",
                to="eft_app.debitaccount",
            ),
        ),
        migrations.AddField(
            model_name="eftbatch",
            name="file_reference",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="eftbatch",
            name="generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eftbatch",
            name="generated_file",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="eftbatch",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="efttransaction",
            name="cost_center",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="efttransaction",
            name="employee_number",
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="efttransaction",
            name="narration",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="efttransaction",
            name="national_id",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="efttransaction",
            name="reference_number",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="efttransaction",
            name="source_reference",
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name="supplier",
            name="cost_center",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="supplier",
            name="credit_reference",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="supplier",
            name="employee_number",
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="supplier",
            name="national_id",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="supplier",
            name="source",
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name="bank",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="banks_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bank",
            name="swift_code",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$",
                        "Invalid SWIFT code",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="eftbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING", "Pending Authorization"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("EXPORTED", "Exported to RBM"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="efttransaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="efttransaction",
            name="debit_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="eft_app.debitaccount",
            ),
        ),
        migrations.AlterField(
            model_name="efttransaction",
            name="scheme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="eft_app.scheme",
            ),
        ),
        migrations.AlterField(
            model_name="efttransaction",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="eft_app.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="efttransaction",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="eft_app.zone",
            ),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schemes",
                to="eft_app.zone",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="suppliers",
                to="eft_app.bank",
            ),
        ),
        migrations.CreateModel(
            name="ApprovalAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXPORTED", "Exported"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("remarks", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="eft_app.eftbatch",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.RemoveField(
            model_name="efttransaction",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="efttransaction",
            name="updated_at",
        ),
    ]
