# Generated by Django 5.0.6 on 2026-02-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eft_app", "0002_remove_bank_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="efttransaction",
            name="narration",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="efttransaction",
            name="reference_number",
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name="efttransaction",
            name="source_reference",
            field=models.CharField(max_length=18),
        ),
    ]
