# Generated by Django 5.0.6 on 2026-02-28 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eft_app", "0003_alter_efttransaction_narration_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eftbatch",
            name="fm_remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="eftbatch",
            name="fm_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eftbatch",
            name="fm_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches_fm_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="approvalauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Submitted for Finance Manager Review"),
                    ("FM_REVIEWED", "Reviewed by Finance Manager"),
                    ("FM_REJECTED", "Rejected by Finance Manager"),
                    ("APPROVED", "Approved by Director of Finance"),
                    ("REJECTED", "Rejected by Director of Finance"),
                    ("EXPORTED", "Exported to RBM"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eftbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_FM", "Pending Finance Manager"),
                    ("PENDING_DIRECTOR", "Pending Director of Finance"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("EXPORTED", "Exported to RBM"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
