# Generated by Django 5.0.6 on 2026-04-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eft_app", "0004_eftbatch_fm_remarks_eftbatch_fm_reviewed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eftbatch",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("OBDXPMN", "Payment File - Domestic Suppliers"),
                    ("OBDXFX", "Foreign Payment File - Cross Border"),
                    ("OBDXRM", "Remittance File - Intra-account Transfers"),
                    ("OBDXRP", "Remittance with PRN - Tax Payments to MRA"),
                    ("OBDXSF", "Salary File - Employee Payments"),
                ],
                default="OBDXPMN",
                help_text="OBDX file type determines the prefix of the exported file",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="eftbatch",
            name="remarks",
            field=models.TextField(blank=True, help_text="Director's remarks"),
        ),
        migrations.AlterField(
            model_name="eftbatch",
            name="batch_name",
            field=models.CharField(
                help_text="Custom part of the OBDX filename (max 50 chars including underscores)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="eftbatch",
            name="file_reference",
            field=models.CharField(
                blank=True,
                help_text="RBM File Reference (e.g., WTC01-31.01.2023)",
                max_length=16,
            ),
        ),
    ]
