# Generated by Django 5.0.6 on 2026-04-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eft_app", "0005_eftbatch_file_type_eftbatch_remarks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eftbatch",
            name="batch_reference",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
